### ISSUE TITLE
heroku compatible

### ISSUE THREAD

**Issue by mohitjoshi155** [gjhenrique/telegram-bot-torrents#2]
how to deploy this app on heroku?
can u make it heroku compatible please?

**Comment by gjhenrique** [comment]
Hmm, not sure how to deploy rust apps on heroku.

Probably you can find an specific buildpack related to rust, such as (this)[https://github.com/emk/heroku-buildpack-rust].

Just be careful on using free heroku because your dyno will be killed and you won't receive new messages. Permanent dynos start at 7 dollars a month.
