### ISSUE TITLE
bot stops working on being added to group

### ISSUE THREAD

**Issue by mohitjoshi155** [gjhenrique/telegram-bot-torrents#3]
bot stops working as soon as you add it to the group it even stops working in personal message
even after adding TELEGRAM_ALLOWED_GROUPS it didnt work

**Comment by gjhenrique** [comment]
hi @mohitjoshi155 

Thanks for reporting this.

This is indeed an issue. Probably something was added on telegram side that's breaking the parsing of the [telegram library](https://github.com/telegram-rs/telegram-bot). Since I already have the bot on a group, I didn't receive the new message.

By tracing the calls, I can see that the issue is related to the [my_chat_member](https://core.telegram.org/bots/api#chatmemberupdated) message.

I've been thinking of moving the telegram logic to the [frankenstein](https://github.com/ayrat555/frankenstein) library, which is maintained now.
Ofc, PRs are always welcome. For now, you'll need to use it only for private messages. I'll update it here once I have migrated.

**Comment by gjhenrique** [comment]
Actually, there is a workaround  for this.

After adding the bot to the group, call `https://api.telegram.org/bot<BotToken>/getUpdates?` (can be via curl or browser).
In there you'll see all of your messages.

Then you go the last message and increment the value of `update_id` in the query parameter `offset` of the `getUpdates` call again
`https://api.telegram.org/bot<BotToken>/getUpdates?offset=<value of update_id + 1>`

Confirm that `https://api.telegram.org/bot<BotToken>/getUpdates` won't have any more messages.

This way, you "consume" the broken messages and the bot will continue getting the new messages.

**Comment by gjhenrique** [comment]
Fixed in https://github.com/gjhenrique/telegram-bot-torrents/commit/4c2a05d88dc9f3d0a60959c40c7847d5a0a92b76

Could you check if master is working for you? 
If so, I'll push a new tag to have a new release :wink:

**Comment by mohitjoshi155** [comment]
> Fixed in [4c2a05d](https://github.com/gjhenrique/telegram-bot-torrents/commit/4c2a05d88dc9f3d0a60959c40c7847d5a0a92b76)
> 
> Could you check if master is working for you? If so, I'll push a new tag to have a new release 😉

yes the issue seems to be fixed now ty

**Comment by gjhenrique** [comment]
New fix lives in v0.4.0
